name: Complete Build and Test 

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    services:
      redis:
        image: redis:alpine
        ports:
          - 6379:6379

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          
      - name: Install Node.js Dependencies
        run: npm install
        working-directory: ./backend # Adaptez ce chemin si votre package.json est ailleurs
        
      - name: Run ESLint
        run: npx eslint .
        working-directory: ./backend # Adaptez ce chemin si vos fichiers JS sont ailleurs
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          
      - name: Install Python Dependencies
        run: |
          pip install -r requirements.txt
        working-directory: ./backend # Adaptez ce chemin si votre requirements.txt est ailleurs
