name: Syntax Check and API Integrity

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Python dependencies
        run: pip install -r .github/workflows/requirements.txt

      - name: Check Python syntax
        run: find . -name '*.py' -type f -exec python -m py_compile {} +

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' 

      - name: Install ESLint
        run: npm install -g eslint

      - name: Check JavaScript syntax
        run: eslint .

      - name: Start API
        run: python app.py &

      - name: Run API Integrity Check
        run: |
          # Replace "http://localhost:5000" with the actual URL of your API
          curl http://localhost:5000 # Example of API endpoint
